In [1]:
import subprocess
import numpy as np

In [10]:
id_version_dict = {
    "tabnet": {
        "small":{
            "id": "dsfegk4iempjrzo",
            "versions":[(np.arange(0,10),"1immq7o"),(np.arange(10,30),"f3sx1eb")]
        },
        "medium":{
            "id":"dsde7s94j7arkrx",
            "versions": [(np.arange(0,10),"2wrcmxu"),(np.arange(10,30),"kfmi48a")]
        },
        "large":{
            "id":"ds7ofauive8sfux",
            "versions": [(np.arange(0,10),"6d1hc94"),(np.arange(10,20),"5qkai3i"),(np.arange(20,30),"mg522zn")]
        }
    },
    "xgboost": {
        "small":{
            "id":"ds01701njoa65dj",
            "versions": [(np.arange(0,10),"1ueznvu"),(np.arange(10,30),"0kxwy6o"),(np.arange(30,31),"dbtsdqg")]
        },
        "medium": {
            "id":"dsiyxcdx4065nnb",
            "versions": [(np.arange(0,10),"625jshj"),(np.arange(10,30),"s7md5jq"),(np.arange(30,31),"qpze45e")]
        },
        "large":{
            "id":"dscix08lbbpq2gk",
            "versions": [(np.arange(0,10),"hs6q514"),(np.arange(30,31),"jfejg2i")]
        }
    }
}

In [26]:
id_version_dict

{'tabnet': {'small': {'id': 'dsfegk4iempjrzo',
   'versions': [(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), '1immq7o'),
    (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
            27, 28, 29]),
     'f3sx1eb')]},
  'medium': {'id': 'dsde7s94j7arkrx',
   'versions': [(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), '2wrcmxu'),
    (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
            27, 28, 29]),
     'kfmi48a')]},
  'large': {'id': 'ds7ofauive8sfux',
   'versions': [(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), '6d1hc94'),
    (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), '5qkai3i'),
    (array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), 'mg522zn')]}},
 'xgboost': {'small': {'id': 'ds01701njoa65dj',
   'versions': [(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), '1ueznvu'),
    (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
            27, 28, 29]),
     '0kxwy6o'),
    (array([30]), 'dbtsdqg')]},
  'medium': {'id':

In [11]:
def get_id_version(model,size,eval_no):
    model_size_v_dict = id_version_dict[model][size]
    idd = model_size_v_dict["id"]
    versions = model_size_v_dict["versions"]
    for eval_range, version_id in versions:
        if eval_no in eval_range:
            return f"{idd}:{version_id}"

In [5]:
base_cmd = ["gradient","datasets","files", "get",]

def store_metrics_for(model,size,eval_start=0,eval_end=10):
    for eval_no in range(0,30):
        target_path = f"../results/{model}/{size}/{eval_no}/metrics.p"
        source_path = f"{eval_no}/metrics.p"
        id_version = get_id_version(model,size,eval_no)
        cmd = base_cmd + ["--id",id_version,"--target-path", target_path, "--source-path", source_path]
        subprocess.run(cmd)

In [28]:
for model in ["tabnet","xgboost"]:
    for size in ["small","medium","large"]:
        store_metrics_for(model,size)

⠼ Downloading files: /26/metrics.p (0)

KeyError: 'large'

In [31]:
store_metrics_for("xgboost","large",eval_start=0,eval_end=10)

⠴ Downloading files: /9/metrics.p (0)

TypeError: expected str, bytes or os.PathLike object, not NoneType

## Download feature importances

In [12]:
def store_feature_importance_for(model,size,eval_no,filename="feature_and_res.p"):
    target_path = f"../results/{model}/{size}/{eval_no}/{filename}"
    source_path = f"{eval_no}/{filename}"
    id_version = get_id_version(model,size,eval_no)
    cmd = base_cmd + ["--id",id_version,"--target-path", target_path, "--source-path", source_path]
    subprocess.run(cmd)

In [16]:
for size,eval_no in zip(["large","medium","small"],[18,13,18]):
    store_feature_importance_for("tabnet",size,eval_no)

⠇ Downloading files: /18/feature_and_res.p (0)


Aborted!


KeyboardInterrupt: 

In [ ]:
for size,eval_no in zip(["medium","small"],[30,30]):
    store_feature_importance_for("xgboost",size,eval_no,"features.p")

⠴ Downloading files

In [14]:
size="large"
eval_no=30
store_feature_importance_for("xgboost",size,eval_no,"features.p")

⠼ Downloading files